# app/views/api/v1/amigo_locations/_location.json.jbuilder

json.extract! location,
:id,
:address,
:floor,
:street_number,
:street_name,
:room_no,
:apartment_suite_number,
:city_sublocality,
:city,
:state_province_subdivision,
:state_province,
:state_province_short,
:country,
:country_short,
:postal_code,
:postal_code_suffix,
:post_box,
:latitude,
:longitude,
:time_zone,
:created_at,
:updated_at